//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shastra.Hydra.HydraStressTestClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shastra.Hydra.HydraStressTestClient.MessageData", typeof(MessageData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT is.
        /// </summary>
        internal static string data1 {
            get {
                return ResourceManager.GetString("data1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ``It was the prospect of constant society, and good society,&apos;&apos; he added, ``which was my chief inducement to enter the ----shire. I knew it to be a most respectable, agreeable corps, and my friend Denny tempted me farther by his account of their present quarters, and the very great attentions and excellent acquaintance Meryton had procured them. Society, I own, is necessary to me. I have been a disappointed man, and my spirits will not bear solitude. I must have employment and society. A military life is not [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string data10 {
            get {
                return ResourceManager.GetString("data10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ``Be not alarmed, Madam, on receiving this letter, by the apprehension of its containing any repetition of those sentiments, or renewal of those offers, which were last night so disgusting to you. I write without any intention of paining you, or humbling myself, by dwelling on wishes, which, for the happiness of both, cannot be too soon forgotten; and the effort which the formation and the perusal of this letter must occasion should have been spared, had not my character required it to be written and read.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string data11 {
            get {
                return ResourceManager.GetString("data11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to universally.
        /// </summary>
        internal static string data2 {
            get {
                return ResourceManager.GetString("data2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acknowledged, that a.
        /// </summary>
        internal static string data3 {
            get {
                return ResourceManager.GetString("data3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single man in possession of a good fortune must be in want.
        /// </summary>
        internal static string data4 {
            get {
                return ResourceManager.GetString("data4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However little known the feelings or views of such a man may be on his first entering a neighbourhood,.
        /// </summary>
        internal static string data5 {
            get {
                return ResourceManager.GetString("data5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why, my dear, you must know, Mrs. Long says that Netherfield is taken by a young man of large fortune from the north of England; that he came down on Monday in a chaise and four to see the place, and was.
        /// </summary>
        internal static string data6 {
            get {
                return ResourceManager.GetString("data6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ``You are over-scrupulous, surely. I dare say Mr. Bingley will be very glad to see you; and I will send a few lines by you to assure him of my hearty consent to his marrying which ever he chuses of the girls; though I must throw in a good word for my little Lizzy.&apos;&apos;
        ///``I desire you will do no such thing. Lizzy is not a bit better than the others; and I am sure she is not half so handsome as Jane, nor half so good humoured as Lydia. But you are always giving her the preference.&apos;&apos;.
        /// </summary>
        internal static string data7 {
            get {
                return ResourceManager.GetString("data7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In describing to her all the grandeur of Lady Catherine and her mansion, with occasional digressions in praise of his own humble abode and the improvements it was receiving, he was happily employed until the gentlemen joined them; and he found in Mrs. Philips a very attentive listener, whose opinion of his consequence increased with what she heard, and who was resolving to retail it all among her neighbours as soon as she could. To the girls, who could not listen to their cousin, and who had nothing to do b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string data8 {
            get {
                return ResourceManager.GetString("data8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Wickham did not play at whist, and with ready delight was he received at the other table between Elizabeth and Lydia. At first there seemed danger of Lydia&apos;s engrossing him entirely for she was a most determined talker; but being likewise extremely fond of lottery tickets, she soon grew too much interested in the game, too eager in making bets and exclaiming after prizes, to have attention for any one in particular. Allowing for the common demands of the game, Mr. Wickham was therefore at leisure to tal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string data9 {
            get {
                return ResourceManager.GetString("data9", resourceCulture);
            }
        }
    }
}
